# If you come from bash you might have to change your $PATH.
export PATH=$PATH:bin
export PATH=$PATH:node_modules/.bin
export PATH=$PATH:vendor/bin
export PATH=$PATH:$HOME/.composer/vendor/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:"$HOME/.platformsh/bin"
export PATH="$HOME/.bin:$PATH"

for zsh_source in $HOME/.zsh/configs/*.zsh; do
  source $zsh_source
done

for function in $HOME/.zsh/functions/*; do
  source $function
done

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
